name: Build and deploy to dev
on:
  workflow_call:
    inputs:
      config-file-name:
        required: true
        type: string
    secrets:
      api_deploy_token:
        required: true
  workflow_dispatch:
    inputs:
      config-file-name:
        description: 'Config-fil som skal deployes'
        required: true
        default: 'mock'
        type: choice
        options:
          - 'dev'
          - 'mock'


jobs:
  build:
    name: Build and deploy to dev
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: "https://npm.pkg.github.com"
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Run tests
        run: npm run test
      - name: Build application
        run: npm run build

      - name: Create and release tag
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-and-release-tag@master
        with:
          prefix: ${{ github.event.inputs.config-file-name }}-

      - name: Build and push Docker Image
        uses: navikt/sosialhjelp-ci/actions/build-and-push-docker-image@master
        with:
          image-name: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-version: ${{ steps.artifact-version.outputs.artifact-version }}

      - name: Deploy til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/dev/${{ github.event.inputs.config-file-name }}.yaml
          CLUSTER: dev-gcp
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.DOCKER_TAG }}