#name: Deploy til prod-gcp
#on:
#  workflow_run:
#    workflows: ["Build image"]    # Venter pÃ¥ at bygget for prod er ferdig
#    branches: [master]
#    types:
#      - completed
#
#jobs:
#  deploy:
#    name: Deploy to prod-gcp
#    runs-on: ubuntu-latest
#    env:
#      DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
#    steps:
#      - uses: actions/checkout@v3
#      - name: Create artifact version
#        id: artifact-version
#        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master
#      - name: Create docker image tags
#        run: |
#          echo "DOCKER_TAG=${{ env.DOCKER_IMAGE }}:${{ steps.artifact-version.outputs.version }}" >> $GITHUB_ENV
#      - name: deploy til prod-gcp
#        uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          RESOURCE: nais.yaml
#          CLUSTER: prod-gcp
#          VARS: nais/prod/prod-gcp.json
#          REF: ${{ github.sha }}
#          PRINT_PAYLOAD: true
#          IMAGE: ${{ env.DOCKER_TAG }}
